### PR TITLE
Analyse the "Text" column - Output text length, word count and offset differences in notebook file

### PR DESCRIPTION
**Pull request by mtauer**

### CODE REVIEW

**Review by boris-tschirschwitz — APPROVED** [review]
This looks excellent.
These features will be interesting to use for example if we want to work with relative distances (e.g. offset/text_length) instead of total distances.

So far we always try to clean the output from the notebook before committing it to make it easier to compare and merge.

It's so nice to see how quickly the notebook runs, it's almost instantaneous.

**Comment by boris-tschirschwitz** [comment]
I guess we have to decide on how to use the three data files: development, test, and validation.
Maybe start with the development file for learning? Later we can probably add a good chunk of the test data to the learning data, as they are both 2000 entries long. The shorter validation data we should probably not touch until the end.

**Comment by boris-tschirschwitz** [comment]
You can replace your map functions with pandas collection methods.
E.g. instead of
`gap_df['Text-len'] = gap_df['Text'].map(lambda x: len(x))`
you can do a
`gap_df['Text-len'] = gap_df['Text'].str.len()`.

I saw this in the one analysis example on the Kaggle site I looked at, but I don't really understand what the 'str' method is doing.

@erwald @asharov do you understand the 'str' method?

**Comment by mtauer** [comment]
> You can replace your map functions with pandas collection methods.
> E.g. instead of
> `gap_df['Text-len'] = gap_df['Text'].map(lambda x: len(x))`
> you can do a
> `gap_df['Text-len'] = gap_df['Text'].str.len()`.
> 
> I saw this in the one analysis example on the Kaggle site I looked at, but I don't really understand what the 'str' method is doing.
> 
> @erwald @asharov do you understand the 'str' method?

@boris-tschirschwitz thanks for the tip. I think `str` returns a `StringMethods` instance. http://pandas.pydata.org/pandas-docs/version/0.15.2/api.html#string-handling.

**Comment by mtauer** [comment]
@boris-tschirschwitz I integrated your suggestions. Please review again.

**Review by boris-tschirschwitz — APPROVED** [review]

**Pull request merged**
